name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install frontend dependencies
        run: npm ci --legacy-peer-deps

      - name: Build project
        run: npm run build
        
      - name: Clone Selenium Project
        run: |
          git clone https://github.com/uezili/selenium-project-test.git

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Start HTTP server
        run: npm run preview &

      - name: Run Selenium Tests
        working-directory: ./selenium-project-test
        run: mvn clean test

      - name: List files
        run: ls -la ./dist

      - name: Deploy 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
